### PR TITLE
Correct http_acl resource updates when using only user (no sddl)

### PR DESCRIPTION
**Pull request by kamaradclimber**
Change-Id: I9a894174f439ba201feae53d545f44669f06a20a
JIRA: WTH-1395

### CODE REVIEW

**Comment by kamaradclimber** [comment]
cc @aboten

**Review by Annih — CHANGES_REQUESTED** [review]
Could you add a real commit message describing the issue? Especially if we want to merge this upstream.

**Comment by kamaradclimber** [comment]
let me know if you need more info / changes :)

**Review by Annih — APPROVED** [review]
LGTM

**Pull request merged**
